### ISSUE TITLE
other projects

### ISSUE THREAD

**Issue by letarg0** [GameboyZero/GabozePocaio#10]
Here is other project: https://www.clockworkpi.com/

Is possible to add more keys for You project? 
for example more than 10.

Second idea is rottor, potenciometer adjusting some values (cilinder potenciometer)
or for game for example **Tempest** https://www.gamespot.com/tempest/

**Comment by 32teeth** [comment]
Not sure i understand what you mean by more keys?

**Comment by gingerbeardman** [comment]
He means input buttons @32teeth

**Comment by 32teeth** [comment]
Feature Request Noted.
Closing
