### ISSUE TITLE
For the Gaboze Pocaio Plus too be labeled "Open Source" wouldn't you need to publish board files? It is not open source if you only allow us to get a pcb made and not see what actually goes into it.

### ISSUE THREAD

**Issue by KonnorJ** [GameboyZero/GabozePocaio#12]

**Comment by 32teeth** [comment]
Thanks @KonnorJ 
They are in the [GabozePocaio/eagle/Plus folder](https://github.com/GameboyZero/GabozePocaio/tree/master/eagle/Plus)
_Don't forget to read the [**LICENSE.md**](https://github.com/GameboyZero/GabozePocaio/blob/master/)_
