### ISSUE TITLE
The 'releases' section can lead to confusion, since you have to unzip to write the img file using 'dd'

### ISSUE THREAD

**Issue by jesusignazio** [GameboyZero/GabozePocaio#14]
The img file is not the .gz as explained in the wiki:

`$ file GabozePocaioOfficial.gz
GabozePocaioOfficial.gz: gzip compressed data, last modified: Thu Jul 26 23:32:00 2018, max speed, from Unix, original size -329777152
`

`$ file GabozePocaioOfficial 
GabozePocaioOfficial: DOS/MBR boot sector; partition 1 : ID=0xe, active, start-CHS (0x40,0,1), end-CHS (0x3cf,3,32), startsector 8192, 116736 sectors; partition 2 : ID=0x83, start-CHS (0x3d0,0,1), end-CHS (0x3ff,63,32), startsector 124928, 7619584 sectors`

**Comment by 32teeth** [comment]
You issue title and description talk about two different things
Both files, img and gz where created using ApplePi Baker

You are NOT meant to unzip the gz file as per wiki
