### ISSUE TITLE
Missing Eagle Library?

### ISSUE THREAD

**Issue by Uplinkpro** [GameboyZero/GabozePocaio#9]
Every time I try to open this up in Eagle I'm missing a "GBA" library, I've added all the lbrs you have provided with no luck.

**Comment by 32teeth** [comment]
Hmm, the only one part that uses that is the volume potentiometer. I’ll look into it

**Comment by 32teeth** [comment]
Ah, you are opening the layout file. It has been stripped of most components and is indented for “layout” purposes.

**Comment by Uplinkpro** [comment]
Gotcha , the problem with the board now is if you hit the up button it will also hit the right or left button if you make that little change you see I made in the layout, that should correct the issue I believe, Also would be neat to try to use a USB Type-C connector on this but that's another thing all together.

**Comment by 32teeth** [comment]
| ![Board-Top](https://raw.githubusercontent.com/GameboyZero/GabozePocaio/master/images/Board-Top.png) |
|:--:|
| *[Conductive Button Library](https://github.com/GameboyZero/GabozePocaio/blob/master/lbr/ConductiveButtons.lbr)* |

**Comment by lipomos** [comment]
hi 32
Your great job is very good
so I want the perfect full eagle file.
Can you do that? please

**Comment by goc335** [comment]
The GBA library is still not available on the library folder. And many og the components are missing og the schematic in the eagle files.
